IFCI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gedci.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gedci/urls.py
from django.urls import path
from . import views as gedci_views

app_name = 'gedci'

urlpatterns = [
    path('', gedci_views.Accueil.as_view(), name='accueil'),
    path('cdp/<slug:filtre>/<slug:order>', gedci_views.Chefs2Pole.as_view(), name='cdp'),
    path('conseillers/<slug:filtre>/<slug:order>/<slug:acteur>', gedci_views.Conseillers.as_view(), name='conseillers'),
    path('conseillers2/<slug:filtre>/<slug:order>/<slug:acteurid>', gedci_views.Conseillers2.as_view(), name='conseillers2'),
    path('etatsdos/<int:docid>', gedci_views.EtatsDosView.as_view(), name="etatsdos"),
    path('importation/', gedci_views.ImportationView.as_view(), name='importation'),
    path('stats/', gedci_views.Stats.as_view(), name='stats'),
]

gedci/forms.py
from django.forms import ModelForm
from gedci.models import Dossier, Importation


class ImportationForm(ModelForm):
    class Meta:
        model = Importation
        fields = '__all__'

class DossierForm(ModelForm):
    class Meta:
        model = Dossier
        fields = '__all__'

        # class LoginForm(forms.Form):
#     login_name = forms.CharField(label='Login Name', max_length=100)
#     mot_de_passe = forms.CharField(label='Mot de passe', max_length=100)
    

gedci/gedcilib/forms.py
from .scraptools import find_elt_by, find_elts_css
import pandas as pd

def check(elt):
    """active un chekbox non activé et sinon le laisse activé"""
    if not elt.get_attribute('checked'):
        elt.click()

def decheck(elt):
    """active un chekbox non activé et sinon le laisse activé"""
    if elt.get_attribute('checked'):
        elt.click()


def set_radio(i, list):
    """given a list an an indice set the ieme element of that list"""
    elts = list.find_elements_by_tag_name('label')
    assert i < len(elts)
    elts[i].click()

def get_selections(d):
    """retourne un dict avec les noms et les selections ( choix avec liste déroulante)"""
    D = {}
    for e in find_elts_css(d, 'select'):
        name = e.get_attribute('id')
        if name:
            D[name] = e

    return D

def get_options(d, idselect):
    """Renvoie une série avec les options et leur valeurs respective dans la liste d'options
idliste est un string id du tag select"""
    elts = find_elt_by('ID', d, idselect)
    D = {}
    for elt in elts.find_elements_by_tag_name('option'):
        D[elt.get_attribute('value')] = elt.text

    s = pd.Series(D)
    s.name = 'idselect'
    s.index.name = 'value'
    return s

def set_option(i, list, d=None):
    """given a list an an indice set the ieme element of that list
    la liste peut un in string si d est donnée"""
    if d:
        sels = get_selections(d)
        list=sels[list]
        elts = list.find_elements_by_tag_name('option')
        assert i < len(elts)
        elts[i].click()


# #### Remplissage du formulaire de recherche ####
def remplir_formulaire_recherche(d, default=True):
    """Fait un remplissage par defaut du formulaire"""
    if default:
        check(find_elt_by('ID', d, 'choixDossierCandidature'))
        decheck(find_elt_by('ID', d, 'choixRefusCandidatException'))
        check(find_elt_by('ID', d, 'choixDossierPreconsulaire')) 
        check(find_elt_by('ID', d, 'choixAcceptationElectronique'))
        check(find_elt_by('ID', d, 'choixProgrammeEchange'))
        check(find_elt_by('ID', d, 'choixAcceptationPapier'))
        decheck(find_elt_by('ID', d, 'horsCatalogue'))
        decheck(find_elt_by('ID', d, 'choixCompteSansDossiers'))
        decheck(find_elt_by('ID', d, 'dapBlanche'))
        decheck(find_elt_by('ID', d, 'dapBlancheVoeuUn'))
        decheck(find_elt_by('ID', d, 'dapBlancheVoeuDeux'))
        decheck(find_elt_by('ID', d, 'dapBlancheVoeuTrois'))
        decheck(find_elt_by('ID', d, 'dapJaune'))
        decheck(find_elt_by('ID', d, 'dapJauneVoeuUn'))
        decheck(find_elt_by('ID', d, 'dapJauneVoeuDeux'))
        decheck(find_elt_by('ID', d, 'polytech'))
        decheck(find_elt_by('ID', d, 'iut'))
        decheck(find_elt_by('ID', d, 'autre'))
        decheck(find_elt_by('ID', d, 'fle'))
        decheck(find_elt_by('ID', d, 'cbDateEtatDossier'))  
        decheck(find_elt_by('ID', d, 'cbDatePaiement'))
        decheck(find_elt_by('ID', d, 'cbDateEntretien'))
        check(find_elt_by('ID', d, 'cbMessagesNonTraites'))
        decheck(find_elt_by('ID', d, 'criteres.dispenseTestFrancais'))
        decheck(find_elt_by('ID', d, 'criteres.filtreNiveauFrancais')) 
        decheck(find_elt_by('ID', d, 'criteres.rechercheDifferee'))

        #### boutons radios
        # soumis 1, indifférent 6
        set_radio(6, find_elt_by('ID', d, 'listeEtatsDossier')) 
        set_radio(4, find_elt_by('ID', d, 'listeEtatsPaiement'))
        set_radio(4, find_elt_by('ID', d, 'listeEtatsEntretien'))
        # pour les liste selection (déroulantes) au laisse au defautl
        #### select
        set_option(0, "listeAntennes", d)
        set_option(0, "criteres.acceptPapierAutreCas", d)
        set_option(0, "typeDiplome", d)
        set_option(0, "typeFormationFle", d)
        set_option(0, "criteres.idObjetEtudiant", d)
        set_option(0, "exemptionEntretienPaiement", d)
        set_option(0, "criteres.statutBourse", d)
        set_option(0, "criteres.statutAutre", d)
        set_option(0, "criteres.niveauFrancaisMin", d)
        set_option(0, "criteres.niveauFrancaisMax", d)


def lance_recherche_directe(d):
    # themis lance la recherche
    find_elt_by('ID', d, 'submitButtonRechercherParCriteres').click()

def lance_recherche_differee(d, bname=None):
    """si basename is None, utiliser gedci_export_ y ajoute un time stamp lance la recherche différée et renvois le nom du fichier qui sera téléchargé """
    # Thèmis coche la case 'Recherche différée'
    check(find_elt_by('ID', d, 'criteres.rechercheDifferee'))

    # Thèmis crée le nom du fichier
    # Thèmis récupère la date du moment et la sauvegarde dans une chaine
    if bname is not None:
        now = pd.Timestamp.now().round('60s').strftime("%Y%m%d_%H%M")
        bname = f'{bname}_'+now
        
        # Thèmis renseigne le champs Nom du fichier
        # utilise l'heure de paris par défaut. UTC +1 pour nommer le fichier
        input = find_elt_by('ID', d, ('criteres.nomFichierRechercheDifferee'))
        input.clear()
        input.send_keys(bname)

    # Thèmis envois notre requête
    find_elt_by('ID', d, 'submitButtonRechercherParCriteres').click()
    
    if bname is None:
        return None
    else:
        return bname+'.xls'
    

gedci/views.py
from django.shortcuts import render, redirect
from gedci.models import UserGEDCI, Attribution, Dossier, Importation, EtatAtt, AbstractEtat
from gedci.forms import ImportationForm, DossierForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
import logging
from django.views import generic
from gedci.gedcilib import func4views as v
from gedci.gedcilib import settings as S

# ############### Main view classes ################

class Accueil(LoginRequiredMixin, View):

    def get(self, request):
        # J'arrive ici que si mon user est identifié
        logging.info(f"GET {request.user.groups}")

        if len(request.user.groups.filter(name__in=S.GROUPS_CHEF)):
            return redirect('/cdp/soumis/doc')

        elif len(request.user.groups.filter(name__in=S.GROUPS_CONSEIL)):
            return redirect(f'/conseillers/tous/doc/{request.user.id}')


class Chefs2Pole(LoginRequiredMixin, View):
    """Gére les manip avant l'affichage de l'accueil. Si new alors fait un nouvel accueil."""

    def post(self, request, order="numDos", filtre="tous"):

        try:
            acteurid = request.POST['acteurs'].split('-')[1]
            # on met à jour les attribution
            _ = v.set_attributions(request, acteurid=acteurid,
                                   docIds=v.get_checkbox_id(request))
        except IndexError as ie:
            pass
            
        return self.get(request, order, filtre)
        
    def get(self, request, order="numDos", filtre="tous"):

        # on récupère les dossiers
        context = v.get_Dos_context(order=order,
                                    filtre=filtre)

        # pagination
        context['dataset'] = v.set_pagination(request=request,
                                              dataset=context['dataset'],
                                              default_page=1,
                                              max_page=100)

        # on ajoute le context pour le menu des chefs de poles
        context.update(v.cdp_menu_context())

        return render(request, 'gedci/cdp.html', context)


class Stats(LoginRequiredMixin, View):
    def get(self, request):
        try:
            importation = Importation.objects.all().latest('dateCrea')
        except Exception as e:
            # devrait toujours en avoir une même nulle
            raise e
        # importForm = ImportationForm()
        cols = ["dateCrea", "precedente", "nom_fichier_import", "date_fichier_import", "nb_dossiers", "nb_nouveaux_docs", "nb_updated_docs", "nb_paiements_valides", "nb_visa_renseignes", "nb_scac_instruit", "nb_favorables", "nb_defavorables", "nb_entretenus2", "nb_soumissions", "nb_validations", "nb_entretiens_autorises", "nb_entretiens_valides", "nb_entretiens_demandes", "nb_entretiens_planifie", "nb_entretiens_annules", ]
        importForm = {k.replace("_", " "):v for (k,v) in importation.__dict__.items() if k in cols}

        return render(request, 'gedci/stats.html', context={'imports': importForm.items()})


class ImportationView(LoginRequiredMixin, View):

    def get(self, request):
        context = {}
        context['dataset'] = Importation.objects.order_by('-dateCrea')
        context['order'] = 'doc'
        context.update(v.cdp_menu_context())

        context['dataset'] = v.set_pagination(request=request,
                                              dataset=context['dataset'],
                                              default_page=1,
                                              max_page=1)

        return render(request, 'gedci/importations.html', context=context)
    
class Conseillers2(LoginRequiredMixin, View):

    def post(self, request, filtre, order, acteurid):

        acteur = UserGEDCI.objects.get(pk=acteurid)
        docIds = v.get_checkbox_id(request)

        _ = v.maj_attributions(acteur=acteur,
                               docIds=docIds,
                               etatMaj=request.POST['action'])

        return self.get(request, filtre, order, acteurid)
    
    def get(self, request, filtre, order, acteurid):

        acteur = v.get_model_instance(UserGEDCI, acteurid)
        
        etatAttChoix = set(EtatAtt.CHOIX) - set(AbstractEtat.CHOIX)

        filtre = 'tous' if filtre is None else filtre
        order = 'doc' if order is None else order
        
        context = {"actions": etatAttChoix,
                   "dataset": v.get_docAtt(acteur, order, filtre),
                   "filtre": filtre,
                   "order": order,
                   "acteur": acteur,
                   "acteurid": acteurid}

        context.update(v.cdp_menu_context())
        # pagination
        context['dataset'] = v.set_pagination(request=request,
                                              dataset=context['dataset'],
                                              default_page=1,
                                              max_page=100)

        return render(request, 'gedci/conseillers2.html', context=context)

    

class Conseillers(LoginRequiredMixin, View):

    def post(self, request, filtre, order, acteur):

        acteur = UserGEDCI.objects.get(pk=request.user.pk)
        docIds = v.get_checkbox_id(request)

        _ = v.maj_attributions(acteur=acteur,
                               docIds=docIds,
                               etatMaj=request.POST['action'])

        return self.get(request, filtre, order, acteur)
    
    def get(self, request, filtre, order, acteur):

        acteur = request.user
        etatAttChoix = set(EtatAtt.CHOIX) - set(AbstractEtat.CHOIX)

        filtre = 'tous' if filtre is None else filtre
        order = 'doc' if order is None else order
        
        context = {"actions": etatAttChoix,
                   "dataset": v.get_docAtt(acteur, order, filtre),
                   "filtre": filtre,
                   "order": order,
                   "acteur": acteur}

        # pagination
        context['dataset'] = v.set_pagination(request=request,
                                              dataset=context['dataset'],
                                              default_page=1,
                                              max_page=100)

        return render(request, 'gedci/conseillers.html', context=context)


class EtatsDosView(LoginRequiredMixin, View):

    def get(self, request, docid):
        """Renvois une liste des états du doc"""
        doc = v.get_model_instance(Dossier, docid)
        etatsdocs = list(set(doc.etatsDoc.all()))
        doc._update_DocStat()

        context = v.get_etatsdoc_context(doc, etatsdocs)

        # pagination
        context['dataset'] = v.set_pagination(request=request,
                                              dataset=context['dataset'],
                                              default_page=1,
                                              max_page=100)

        return self.renvois_template(request, context)

    
    def renvois_template(self, request, context):
        if v.est_dans_group(request.user, gname="chef"):
            context.update(v.cdp_menu_context())
            return render(request, 'gedci/detail_etatDos_cdp.html', context=context)
        else:
            context['acteur'] = request.user
            return render(request, 'gedci/detail_etatDos.html', context=context)

gedci/templates/gedci/accueil.html
{% extends "./base.html" %}
{% block titleHead %}  {{title}} {% endblock %}
{% block titleBody %}  Bienvenu {{request.user}} {% endblock %}

{% block content-main %}

{% if request.user.is_authenticated %}
<form id="set_attribution" action="{% url 'gedci:accueil' %}" method="post" >
  {% csrf_token %}

  <select id="actions" name="actions">
    <option value="">---</option>
    {% for action in actions %}
    <option value="action-{{action.id}}">{{action}}</option>
    {% endfor %}
  </select>
  <select id="acteur" name="acteurs">
    <option value="">---</option>
    {% for acteur in acteurs %}
    <option value="acteur-{{acteur.id}}">{{acteur.first_name}} {{acteur.last_name}}</option>
    {% endfor %}
  </select>

  
  <button type="submit" id="ok">Action !</button>

  <table id="tdossiers" class="table table-striped">
    <tr>
      <th> # </th>
      <th>Choix</th>
      <th>Type</th>
      <th>NDossier</th>
      <th>Nom</th>
      <th>Prénom</th>
      <th>Date de Naissance</th>
      <th>Etat</th>
      <th>Attribution</th>
    </tr>
    <!-- <tbody data-toggle="checkboxes" -->
    <!-- 	   data-range="true"> -->

      {% for d in data %}
      <tr>
	<td>{{forloop.counter}}</td>
	<td>
      	  <input type="checkbox" name="checkbox-{{d.id}}" value="{{d.id}}"></td>
	<td>{{d.typeDos}}</td>
	<td>
      	  <a href="https://pastel.diplomatie.gouv.fr/etudesenfrance/dyn/protected/cef/CF_VCA/afficherEtudiantPage.html?sctxid=1-b849d01a3e&rechercheRapide=tdue&numeroCompte={{d.numDos}}"> {{d.numDos}}</a>
	</td>
	<td>{{d.nomEtu}}</td>
	<td>{{d.prenomEtu}}</td>
	<td>{{d.dateNaisEtu}}</td>
	<td>{{d.etat}}</td>
	<td>{{d.attrib}}</td>
      </tr>
      {% endfor %}
    <!-- </tbody> -->
  </table>
</form>
{% else %}
Veuillez vous connectez.
{% endif %}
<script type="text/javascript">
  jQuery(function($) {
    $('#tdossiers').checkboxes('range', true);
});
</script>

{% endblock %}

gedci/templates/gedci/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block head %}{% endblock %}
    {% block head-extra %}{% endblock %}
    {% block head-title %}<title>GEDCI</title>{% endblock %}
  </head>
  <body>
    <div class="container-fluid" >
      <div class="row" >
	<div class="col-sm-3" >
	  <div id="sidebar-nav">
            {% block sidebar %}
	    <div id="date-lieu">Abidjan,</br> {% now "l d F, H:i" %}</div>
	    <hr>
	    {% if request.user.is_authenticated %}
	    <div id="welcome_msg">
	      <div id="user">{{request.user}} Akwabao !</div>
	    </div>
	    <div id="base_menu" class="menu">
	      <ul>
		<li><a href="{% url 'gedci:accueil' %}">Accueil</a></li>
		<li><a href="{% url 'logout' %}">Se déconnecter</a></li>
	      </ul>
	    </div>
	    {% block sidebar-menu %}{% endblock %}
	    {% block sidebar-menu-extra %}{% endblock %}
	    {% else %}
	    {% endif %}
            {% endblock %}
	  </div>
	</div>
	<div  class="col-sm-9" >
	  <div id="title">
	    {% block titleBody %}GEDCI pour Campus France Côte d'Ivoire{% endblock %}
	  </div id="title">
	  <hr>
	  <div id="content">
	    <div id="content-header">{% block content-header %}{% endblock %}</div>
	    <div id="content-main">{% block content-main %}{% endblock %}
	      <div id="content-nav">{% block content-navigation %}{% endblock %}</div>
	    </div>
	  </div>
	  <div id="footer">
	    {% block footer %}{% endblock %}
	  </div>
	</div>
      </div>
      <div id="brand">
	Par Tiko Informatique pour Campus France Côte d'Ivoire, 2018
      {% if request.user.is_authenticated %}
	<contact>Contact: <a href="mailto:malik@kone.ci">contact@tiko.ci</a>, téléphone: +225 09 33 73 78</contact>
		    {% endif %}

	</div>
    </div>
  </body>
</html>

gedci/templates/gedci/base_cdp.html
{% extends "./base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cdp.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/jquery.checkboxes-1.2.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/utils.js' %}"></script>
{% endblock %}


{% block sidebar-menu %}
<div id="menu-administration" class="menu" >
  <div class="header">Administration</div>
  <ul>
    <li><a href=" {% url 'admin:login' %}">Administration</a></li>
    <li><a href=" {% url 'gedci:importation' %}">Statistiques</a></li>
  </ul>

</div>
<div id="menu-attribution" class="menu" >
  <div class="header">Attributions</div>

  <ul>
    {% for a in acteurs %}
    <li><a href="{% url 'gedci:conseillers2' 'encours' order a.pk %}">{{a}}</a></li>
    {% endfor %}
  </ul>
</div>

<div id="menu-filtre" class="menu" >
  <div class="header">Affichages des dossiers</div>
  <ul>
    {% for filtre in filtres %}
    <li><a href="{% url 'gedci:cdp' filtre order %}">
	{% if filtre == 'tous' %}
	TOUS les dossiers
	{% elif filtre == 'def' %}
	Défavorable
	{% elif filtre == 'favorable' %}
	Favorable
	{% elif filtre == 'ensaisie' %}
	En saisie étudiant
	{% elif filtre == 'entretenu' %}
	Synthèse d'entretien terminée
	{% elif filtre == 'instruit' %}
	Instruction SCAC termniée
	{% elif filtre == 'soumis' %}
	Soumis
	{% elif filtre == 'visa' %}
	Décision Visa renseignée
	{% endif %}
    </a></li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

gedci/templates/gedci/cdp.html
{% extends "./base_cdp.html" %}
{% load static %}
{% block titleHead %}  {{title}} {% endblock %}

{% block content-header %}
{% if dataset is None %}
Il n'y a pas de dossiers {{filtre}}
{% else %}
<span>
  {% if filtre == 'tous' %}
  Il y a <b>{{dataset.paginator.count}}</b> dossier{{dataset.paginator.count|pluralize}} en TOUS.
  
  {% else %}
    Il y a <b>{{dataset.paginator.count}}</b>
  dossier(s) {{nom_filtre|upper}}(s)
  {% endif %}
</span>
<span>Mis à jour le {{last_import.dateCrea}}.</span>
{% endif %}

{% endblock %}

{% block content-main %}
<form id="set_attribution" action="{% url 'gedci:cdp' filtre order %}" method="post" >
  {% csrf_token %}
  
  <table id="tdossiers" class="table table-striped">
    <tr>
      <th title="attributions" colspan="2">
	<span>
	  {% if order == "att" %}
	  <a href="{% url 'gedci:cdp' filtre '-att' %}">Trier <span class="upsort">&#x25BC;</span></a>
	  {% elif order == "-att" %}
	  <a href="{% url 'gedci:cdp' filtre 'att' %}">Trier <span class="upsort">&#x25B2;</span></a>
	  {% else %}
	  <a href="{% url 'gedci:cdp' filtre 'att' %}">Trier <span class="upsort">&#x25B2;</span><span class="upsort">&#x25BC;</span></a>
	  {% endif %}
	</span>

	<select id="action" name="action" onchange="maj_liste_acteur(this)">
	  <option value="">---</option>
	  {% for action in actions %}
	  <option value="{{action|lower}}">{{action}}</option>
	  {% endfor %}
	</select>
	
	<select id="acteurs" name="acteurs" class="hide">
	  <option value="">---</option>
	  {% for group in groups_acteurs %}
	  {% for acteur in group.1 %}
	  <option value="acteur-{{acteur.id}}" class="{{group.0.name|lower}} hide">{{acteur.first_name}} {{acteur.last_name}}</option>
	  {% endfor %}
	  {% endfor %}
	</select>
	<button type="submit" id="ok" onclick="exec_attribution(this)">Attribuer</button>
	<button id="select_all">Tous choisir</button>
      </th>

      <th title="trier">      
	{% if order == "doc" %}
	<a href="{% url 'gedci:cdp' filtre '-doc' %}">Dossier <span class="upsort">&#x25BC;</span></a>
	{% elif order == "-doc" %}
	<a href="{% url 'gedci:cdp' filtre 'doc' %}">Dossier <span class="upsort">&#x25B2;</span></a>
	{% else %}
	<a href="{% url 'gedci:cdp' filtre 'doc' %}">Dossier <span class="upsort">&#x25B2;</span><span class="upsort">&#x25BC;</span></a>
	{% endif %}
      </th>

      <th title="trier">      
	{% if order == "typed" %}
	<a href="{% url 'gedci:cdp' filtre '-typed' %}">Type<span class="upsort">&#x25BC;</span></a>
	{% elif order == "-typed" %}
	<a href="{% url 'gedci:cdp' filtre 'typed' %}">Type<span class="upsort">&#x25B2;</span></a>
	{% else %}
	<a href="{% url 'gedci:cdp' filtre 'typed' %}">Type<span class="upsort">&#x25B2;</span><span class="upsort">&#x25BC;</span></a>
	{% endif %}
      </th>

      <th title="trier">      
	{% if order == "nom" %}
	<a href="{% url 'gedci:cdp' filtre '-nom' %}">Nom <span class="upsort">&#x25BC;</span></a>
	{% elif order == "-nom" %}
	<a href="{% url 'gedci:cdp' filtre 'nom' %}">Nom <span class="upsort">&#x25B2;</span></a>
	{% else %}
	<a href="{% url 'gedci:cdp' filtre 'nom' %}">Nom <span class="upsort">&#x25BC;</span><span class="upsort">&#x25B2;</span></a>
	{% endif %}
      </th>

      <th title="trier par nb soumis, puis nb saisies">      
	{% if order == "etat" %}
	<a href="{% url 'gedci:cdp' filtre '-etat' %}">Etat du dossier <span class="upsort">&#x25BC;</span></a>
	{% elif order == "-etat" %}
	<a href="{% url 'gedci:cdp' filtre 'etat' %}">Etat du dossier <span class="upsort">&#x25B2;</span></a>
	{% else %}
	<a href="{% url 'gedci:cdp' filtre 'etat' %}">Etat du dossier <span class="upsort">&#x25BC;</span><span class="upsort">&#x25B2;</span></a>
	{% endif %}
      </th>
      
    </tr>
    <!-- <tbody data-toggle="checkboxes" -->
    <!-- 	   data-range="true"> -->
      {% for datum in dataset %}
      <tr>
	<td>
	  <span>{{forloop.counter}}</span>
	  <input type="checkbox" name="checkbox-{{datum.id}}" value="{{datum.id}}">
	</td>
	<td>
	  <span title="Dernière modification le {{datum.attrib.dateModif}}">{{datum.attrib.action|capfirst}}  {{datum.attrib.etatAtt|lower}} </span> {% if datum.attrib.action is not None %} par {% endif %}
	  <span>{{datum.attrib.acteur}}</span>
	</td>
	<td title="Dossier {{datum.typeDos}}">
      	  <a href="https://pastel.diplomatie.gouv.fr/etudesenfrance/dyn/protected/cef/CF_VCA/afficherEtudiantPage.html?sctxid=1-b849d01a3e&rechercheRapide=tdue&numeroCompte={{datum.numDos}}"> {{datum.numDos}}</a>
	</td>
	<td>{{datum.typeDos}}</td>
	<td title="né le {{datum.dateNaisEtu}}, {{datum.nivoAtteint}}">
	  <span>{{datum.nomEtu}}</span>
	  <span> {{datum.prenomEtu|slice:":20" }}</span>
	</td>
	<td title="{{datum.etat}}">
	  <span><a href="{%url 'gedci:etatsdos' datum.id%}">{{datum.etat.etatD}}</a></span><span> (Pai. {{datum.etat.etatP}})</span>
      </tr>
      {% endfor %}
      <!-- </tbody> -->

  </table>
</form>

<div class="navigation">
  <span class="step-links">
    {% if dataset.has_previous %}
    <a href="?page=1">&laquo; première</a>
    <a href="?page={{ dataset.previous_page_number }}">précédente</a>
    {% endif %}

    <span class="current">
      Page {{ dataset.number }} / {{ dataset.paginator.num_pages }}
    </span>

    {% if dataset.has_next %}
    <a href="?page={{ dataset.next_page_number }}">prochaine</a>
    <a href="?page={{ dataset.paginator.num_pages }}">dernière &raquo;</a>
    {% endif %}
  </span>
</div>


<script type="text/javascript">
  jQuery(function($) {
      $('#tdossiers').checkboxes('range', true);
  });

  jQuery(function($) {
    $('#select_all').on('click', function(e) {
        $('#tdossiers').checkboxes('toggle');
        e.preventDefault();
    });
  });
</script>

{% endblock %}

gedci/templates/gedci/template.html
{% extends "./base.html" %}
{% block titleHead %}  {{title}} {% endblock %}
{% block titleBody %}  Bienvenu {{request.user}} {% endblock %}
{% block content-main %}

{% endblock %}